<?php
include_once("sesionActiva.php"); 
if(isset($_SESSION)){
	unset($_SESSION['admin']);
	unset($_SESSION['nombre']);
	unset($_SESSION['mensaje']);
	session_destroy();
	}header("location:index.php");
?>